import Head from "next/head";
import Header from "@/components/Header";
import GetTable from "@/components/GetTable";

const styles = {
  container: `p-3`,
};
export default function MyCollections() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <GetTable />
    </div>
  );
}
